### ISSUE TITLE
Default install results in redirect loop on all pages

### ISSUE THREAD

**Issue by reydempto** [mgrouchy/django-stronghold#43]
I am using Django 1.7, and the latest stable install of django-blog-zinnia. Once I installed django-stronghold to its default settings via instructions on your readme, I get a redirect loop on all pages and it looks something like this:

'hxxp://example.com/login/?next=/login/%3Fnext%3D/login/%253Fnext%253D/login/%25253Fnext%25253D/login/%2525253Fnext%2525253D/login/%252525253Fnext%252525253D/login/%25252525253Fnext%25252525253D/login/%2525252525253Fnext%2525252525253D/login/%252525252525253Fnext%2525252525252..................... '

I am honestly not sure if this is something to do with stronghold but I would really like to be able to use this middleware either way!

EDIT: Oh my god. I am sorry for even posting this but I think it's because I have my own custom login urls, so stronghold treats it like any other url on my site and hence the loop!

**Comment by mgrouchy** [comment]
haha, no worries! Any questions or problems just let me know!

**Comment by reydempto** [comment]
I am sure this isn't a bug within django-stronghold, but I still can't seem to solve this redirect loop problem. Really not sure what to do. Do you have any advice?

**Comment by reydempto** [comment]
The answer was: I had a bad regex defined in my STRONGHOLD_PUBLIC_URLS. 

For anyone else having this issue, the correct format was:


`<addr>`STRONGHOLD_PUBLIC_URLS = (
    r'^/login.*?$',
)

**Comment by mgrouchy** [comment]
Thanks for the follow up @reydempto.

Cheers!
