### ISSUE TITLE
Support to Django 1.8

### ISSUE THREAD

**Issue by robsonfs** [mgrouchy/django-stronghold#44]
Hi guy,

Are you working in the support for django 1.8?
If not, I can do this in the next two weeks.

Thanks!

**Comment by mgrouchy** [comment]
Hi @robsonfs its not currently tested explicitly in the travis setup. However, I have it running in production in 1.8.4 with no problems.

**Comment by robsonfs** [comment]
thanks...

I'm using django 1.8.2 and doesn't works for me...

I'll check my settings.py and to try again!

**Comment by mgrouchy** [comment]
@robsonfs what issue are you running into, maybe I can help!

**Comment by acer123acer123** [comment]
My urls.py contains this:
from django.contrib.auth.views import login, logout,
url(r'^accounts/login/$',  public(login),  name='login'),

and that works fine. However, the password_reset page requires the user to be logged in.  I have tried to add the url to the urls.py file but can't seem to get it to work.

I modified the "from" line:
from django.contrib.auth.views import login, logout, password_reset

I then added a URL line:
url(r'^user/password/reset/$', public('password_reset', {'post_reset_redirect' : '/user/password/reset/done/'}), name="password_reset"),

OR

url(r'^user/password/reset/$', public('password_reset'), {'post_reset_redirect' : '/user/password/reset/done/'}, name="password_reset"),

Any hints or help would greatly be appreciated.

**Comment by acer123acer123** [comment]
I've been working on this for hours - trying everything I can think of...... And now that I posted this request I see a problem. I have single quotes around password_reset. That won't work.   Here is what it should be (and what is now working for me)

from django.contrib.auth.views import login, logout, password_reset
url(r'^user/password/reset/$', public(password_reset), {'post_reset_redirect' : '/user/password/reset/done/'}, name="password_reset"),

**Comment by mgrouchy** [comment]
Thats interesting. The other option for future views that you might not
write yourself is add it to the STRONGHOLD_PUBLIC_URLS Setting or
STRONGHOLD_PUBLIC_NAMED_URLS.

**Comment by acer123acer123** [comment]
Good idea. Thanks!





Christopher A. Ryan
Christopher.Ryan@gmail.com


Red Hat Certifications:
RHCE, RHCSA, RHCI, RHCX

Other Certifications:
VCE (Vblock) Certified Professional Associate (vce.com)

GPG Information:
gpg:  4096g/214B3A52   0E61 5FF4 37B0 3EB7 DAD7  FE6A EF84 6A89 214B 3A52

**Comment by ActionScripted** [comment]
I ended up wrapping certain methods with `public()` e.g.:

    from stronghold.decorators import public as stronghold_public

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        stronghold_public(auth_views.password_reset_confirm),
        {'template_name': 'accounts/password_reset_confirm.html',
         'post_reset_redirect': 'accounts:password_reset_complete',
         },
        name='password_reset_confirm'),


I couldn't get `STRONGHOLD_PUBLIC_URLS` or `STRONGHOLD_PUBLIC_NAMED_URLS` working as expected. So it works, but it's not quite what I was hoping to accomplish in that I now have a stronghold dependency in my auth app.

What I have/had that wasn't working (accounts is the namespace for my auth stuff):

    STRONGHOLD_PUBLIC_URLS = (
        r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    )
    STRONGHOLD_PUBLIC_NAMED_URLS = (
        'core:home',
        'accounts:login',
        'accounts:logout',
        'accounts:password_reset',
        'accounts:password_reset_complete',
        'accounts:password_reset_confirm',
        'accounts:password_reset_done',
    )

**Comment by mgrouchy** [comment]
hrm. This is strange, I will look into this and track down what the issue is. Thanks for letting me know @ActionScripted.

**Comment by rjschave** [comment]
I just wanted to let you know I ran into the same issue.   Adding password_reset, password_reset_done, and password_reset_complete to the STRONGHOLD_PUBLIC_NAMED_URLS works for me.  Adding password_reset_confirm does not.  I had to wrap with the public () as @ActionScripted suggested.
