### ISSUE TITLE
Public url configuration requires to put "/" in beginning of the pattern

### ISSUE THREAD

**Issue by zatarus** [mgrouchy/django-stronghold#46]
In order to access ^api/brands/$', I had to put
 STRONGHOLD_PUBLIC_URLS = (r'^/api/brands/$',)
instead of:
 STRONGHOLD_PUBLIC_URLS = (r'^api/brands/$',)
which I find more conventional for Django as we define URLs without / in the beginning, especially that is habit caused by urls.py file.

Django version: 1.8.2
Stronghold version: 0.2.7

**Comment by SunilMohanAdapa** [comment]
Django's settings, where URLs are provided, are consistent with strongholds URLs.  Examples:
- Default value of LOGIN_REDIRECT_URL is '/accounts/profile/'
- Default value of LOGIN_URL is '/accounts/login/'

URLs provided in settings are of global context across entire project.  They must be absolute.  Where as URLs provided in `urls.py` could be included in way that they become a sub-path under another path. They are kind of relative to the include path.

I recommend keeping the current behavior and closing this issue.

**Comment by zatarus** [comment]
Reason I suggested that is, users start typing URLs in regular expressions in a new Django project. I believe habit above will always appear as a slowdown. I'm closing this issue unless someone else wants to mention it too.
