### ISSUE TITLE
Support using Django 1.10 new style middleware

### ISSUE THREAD

**Issue by SunilMohanAdapa** [mgrouchy/django-stronghold#53]
Add support for [new style middleware](https://docs.djangoproject.com/en/1.10/releases/1.10/#new-style-middleware) introduced in Django 1.10.  Support for old style middleware will be dropped from Django in the future.  Any application using stronghold can't move using new style middleware until strong supports new style middleware.

Altering existing code to support new style and old style middleware is quite simple as adding a mixin to the existing middleware class.

**Comment by peterfarrell** [comment]
+1 on getting this updated

**Comment by kkampardi** [comment]
Hi folks 8-), I could work on this
My goal is to submit a patch for this fix and then 
fix also  Migrate to new style MIDDLEWARE freedombox/Plinth#549

**Comment by kkampardi** [comment]
As far as I can see django provides us with a deprecation Middlewaremixin:
[https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-middleware](url)

By using the deprecation middleware we can still support older (>= 1.10) versions, although it seems to be a bit hacky(for me at least). 

Also after some [digging](https://docs.djangoproject.com/en/dev/internals/deprecation/) I assume that the MiddlwareMixin will stick around until django version 2.0 where:

> Support for old-style middleware using settings.MIDDLEWARE_CLASSES will be removed.

The solution I have in mind includes:
- Implement MiddlewareMixin if we're able to import it (for >= 1.10 versions)
- Update docs to mention both MIDDLEWARE_CLASSES and MIDLEWARE
- Perhaps write some tests including both old and new style middleware

**Comment by peterfarrell** [comment]
@kkampardi I agree all your 3 bullet points except I think "perhaps write some tests" should be "Write tests" -- tests shouldn't be optional.

**Comment by mgrouchy** [comment]
This is fixed.

**Comment by peterfarrell** [comment]
This was in PR #60 for those interested.

**Comment by peterfarrell** [comment]
@mgrouchy Is there an ETA on this update being rolled out to PyPi?

**Comment by sudeep1801** [comment]
@mgrouchy - please can we get the support for 1.10 style middlewares rolled out to PyPi :)
