### ISSUE TITLE
Python3 tag on PyPi

### ISSUE THREAD

**Issue by aklaver** [mgrouchy/django-stronghold#56]
Would it be possible to add to PyPi entry that django-stronghold  is Python 3 compatible?
I am getting a false negative when I use  the caniusepython3 (https://pypi.python.org/pypi/caniusepython3)  program.

Thanks.

**Comment by mgrouchy** [comment]
Im going to be packaging up a release this weekend. Will tag this weekend! Thanks!

**Comment by ratson** [comment]
@mgrouchy Is there anything blocking the release?

**Comment by orestis** [comment]
Hi, just noting that caniusepython3 reports this as a non-Python 3 compatible.

**Comment by mgrouchy** [comment]
Ive updated this for now, and will make sure its fixed up when I cut a new release! Sorry (had a second kid and startup life slowing me down!)
