### ISSUE TITLE
Django 2.0 Compatibility

### ISSUE THREAD

**Issue by ceorcham** [mgrouchy/django-stronghold#69]
In the conf.py file No module named 'django.core.urlresolvers'
See https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0

Should be update to use the django.urls module

**Comment by underyx** [comment]
Seems like https://github.com/mgrouchy/django-stronghold/pull/68 implements this.

**Comment by ceorcham** [comment]
Yeah, I hope gets merged soon.
