### ISSUE TITLE
Please make a release with Django 2.0 support

### ISSUE THREAD

**Issue by SunilMohanAdapa** [mgrouchy/django-stronghold#72]
Although Django 2.0 support has been added, there is not release yet with this support. We wish to make a Debian package with Django 2.0 support as Django 2.0 is about to released soon into Debian. FreedomBox project especially needs this in time.

Please consider making a new release of stronghold as soon as you can.

**Comment by mgrouchy** [comment]
Hi Sunil,

There has been a release cut with all the latest changes I am pretty sure?
Latest release was 0.3.0 on Jan 11, 2018. Are you sure thats not what you
are looking for?



On Wed, Feb 21, 2018 at 1:47 AM, Sunil Mohan Adapa <notifications@github.com

**Comment by SunilMohanAdapa** [comment]
Sorry I missed the release commit. Could you please tag the release as well so that it appears in the list of [releases](https://github.com/mgrouchy/django-stronghold/releases)?

**Comment by mgrouchy** [comment]
Sure!

**Comment by mgrouchy** [comment]
done!
